export default {
  properties: {
    title: 'Main Settings',
    options: [
      {
        id: 'run_time',
        min: 1,
        max: 10080,
        default: 5760,
        label: 'Simulation world time',
        help: 'Simulated world time in minutes',
        units: 'minutes',
        module: 'simulation',
        experimental: false,
      },
      {
        id: 'init_infection_num = 1920',
        min: 0,
        max: 10000,
        step: 1,
        default: 1920,
        label: 'Initial count of A. fumigatus conidia',
        units: 'conidia',
        module: 'afumigatus',
        experimental: true,
      },
      {
        id: 'validate',
        type: 'checkbox',
        default: true,
        label: 'Perform validation per time step',
        module: 'simulation',
        experimental: false,
      },
    ],
    subsections: {},
  },
  macrophage: {
    title: 'Macrophage',
    options: [
      {
        id: 'init_num_macrophages',
        min: 0,
        max: 1000,
        step: 1,
        default: 100,
        label: 'Initial number of macrophages',
        units: 'macrophages',
        module: 'macrophage',
        experimental: true,
      },
    ],
    subsections: {
      rates: [
        {
          id: 'recruitment_rate',
          min: 0,
          max: 10,
          step: 0.01,
          default: 2,
          label: 'Recruitment rate',
          units: 'macrophage/TODO',
          module: 'macrophage',
          experimental: true,
        },
        {
          id: 'ma_move_rate_rest',
          min: 0,
          max: 10,
          step: 0.01,
          default: 0.036,
          label: 'Movement rate (resting)',
          units: 'TODO',
          module: 'macrophage',
          experimental: true,
        },
        {
          id: 'ma_move_rate_act',
          min: 0,
          max: 10,
          step: 0.01,
          default: 0.036,
          label: 'Movement rate (active)',
          units: 'TODO',
          module: 'macrophage',
          experimental: true,
        },
      ],
      bounds: [
        {
          id: 'max_ma',
          min: 0,
          max: 1000,
          step: 1,
          default: 209,
          label: 'Maximum number of macrophages',
          units: 'macrophages',
          module: 'macrophage',
          experimental: true,
        },
        {
          id: 'min_ma',
          min: 0,
          max: 100,
          step: 1,
          default: 15,
          label: 'Minimum number of macrophages',
          units: 'macrophages',
          module: 'macrophage',
          experimental: true,
        },
        {
          id: 'max_conidia',
          min: 0,
          max: 50,
          step: 1,
          default: 18,
          label: 'Max conidia in phagocyte',
          units: 'conidia',
          module: 'macrophage',
          experimental: true,
        },
      ],
    },
  },
  neutrophil: {
    title: 'Neutrophil',
    options: [
      {
        id: 'init_num_neutrophils',
        min: 0,
        max: 1000,
        step: 1,
        default: 0,
        label: 'Initial number of neutrophils',
        units: 'neutrophils',
        module: 'neutrophil',
        experimental: true,
      },
    ],
    subsections: {
      rates: [
        {
          id: 'recruitment_rate',
          min: 0,
          max: 10,
          step: 0.01,
          default: 2.0,
          label: 'Recruitment rate',
          units: 'neutrophils/TODO',
          module: 'neutrophil',
          experimental: true,
        },
        {
          id: 'n_move_rate_rest',
          min: 0,
          max: 10,
          step: 0.01,
          default: 0.036,
          label: 'Movement rate (resting)',
          units: 'TODO',
          module: 'neutrophil',
          experimental: true,
        },
        {
          id: 'n_move_rate_act',
          min: 0,
          max: 10,
          step: 0.01,
          default: 0.036,
          label: 'Movement rate (active)',
          units: 'TODO',
          module: 'neutrophil',
          experimental: true,
        },
      ],
    },
  },
  erythrocyte: {
    title: 'Erythrocyte',
    options: [
      {
        id: 'init_erythrocyte_level',
        min: 0,
        max: 1000,
        step: 1,
        default: 320,
        label: 'Initial number of erythrocytes',
        help: 'erythrocytes',
        module: 'erythrocyte',
        experimental: true,
      },
    ],
    subsections: {},
  },
  molecules: {
    title: 'Molecules',
    options: [
      {
        id: 'system_concentration',
        min: 0,
        max: 0.00001,
        step: 0.000001,
        default: 0.000002,
        label: 'System Concentration (antiTNFa)',
        units: 'nM',
        module: 'antitnfa',
        experimental: true,
      },
      {
        id: 'system_concentration',
        min: 0,
        max: 0.00001,
        step: 0.000001,
        default: 0.000000,
        label: 'System Concentration (ESTb)',
        units: 'nM',
        module: 'estb',
        experimental: true,
      },
    ],
    subsections: {
      TNFa: [
        {
          id: 'macrophage_secretion_rate',
          min: 0,
          max: 6.0e-20,
          step: 0.01e-20,
          default: 3.22e-20,
          label: 'Macrophage Secretion Rate',
          units: 'mol/(cell*h)',
          module: 'tnfa',
          experimental: true,
        },
        {
          id: 'neutrophil_secretion_rate',
          min: 0,
          max: 6.0e-20,
          step: 0.01e-20,
          default: 1.89e-20,
          label: 'Neutrophil Secretion Rate',
          units: 'mol/(cell*h)',
          module: 'tnfa',
          experimental: true,
        },
        {
          id: 'epithelial_secretion_rate',
          min: 0,
          max: 6.0e-20,
          step: 0.01e-20,
          default: 3.22e-20,
          label: 'Epithelial Secretion Rate',
          units: 'mol/(cell*h)',
          module: 'tnfa',
          experimental: true,
        },
      ],
    },
  },
};
